#!/bin/bash

#GITHUB API URL
API_URL= https://api.github.com"

#Guthub username & Token
USERNAME=$username
TOKEN=$token

#User and Repository name
REPO_OWNER=$1
REPO_NAME=$2

#Function for Github api Get Call
function github_api_get
{
	local endpoint = $1
	local url="${API_URL}/${endpoint}"

	#Send GET request to GITHUB
	curl -s -u "${username}:${token}" "$url"
}

#Function to list user with read access 
function list_user_with_read_access
{
	local endpoint="repos/${REPO_OWNER/${REPO_NAME}/collaborators"
	
	#Fetch the list of collaborators 
	collaborators="$(github_api_get "$endpoint")"

	#Display list of collaborators
	if [[ -z "$collaborators ]]": then 
		echo "No user with read access"
	else
		echo "user with read access"
		echo "$collaborators"
	fi
}

#Main Script

echo "List of users with read access"
list_user_with_read_access

